#!/usr/bin/env python3
"""Generate the docs site's reference pages from the code, so they can't drift from it.

- docs/reference/cli.mdx: every `mobster` command, subcommand, argument and option, with its default, read from
  the argparse parsers (`mobile_agent.__main__.build_parser`).
- docs/reference/mcp-tools.mdx: every tool `mobster mcp` offers, with its description, input schema and MCP
  annotations (read-only or acting), read from `mobile_agent.mcp_server.tools.ToolSet` with the tracks' tools
  loaded (`mobile_agent.tracks.load`, which does no I/O) and `--allow-files` on, so the file tools are listed too.
- docs/llms.txt: the site's index for AI tools (llmstxt.org), served at docs.mobster.dev/llms.txt. Every page in
  docs/docs.json's navigation, in its order, with its frontmatter title and description and a link to its Markdown.
  On 8 Oct 2026 Mintlify served llms-full.txt but answered 404 for its own generated llms.txt (the deployment is set
  to noindex). A committed llms.txt at the docs root replaces the generated one, so the site always has this copy.

Nothing starts: the parsers are built with extensions off (the public tree's commands only, as
mobile_agent/tests/test_docs.py does), and the tool list comes from a ToolSet that never discovers a device or
opens a server. The output depends only on the code: no version, date, path or environment value reaches it.

    python scripts/gen_docs_reference.py           write the pages
    python scripts/gen_docs_reference.py --check   exit 1 if a committed page differs from the code

mobile_agent/tests/test_docs_site.py fails when a committed page is stale.
"""

import argparse
import json
from pathlib import Path
import re
import sys
from unittest import mock

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

DOCS = ROOT / "docs"
REFERENCE = DOCS / "reference"
SITE_URL = "https://docs.mobster.dev"
COMMAND = "python scripts/gen_docs_reference.py"
NOTICE = ("{/* Generated by scripts/gen_docs_reference.py from SOURCE. Don't edit it by hand: change the code, then "
          "run `" + COMMAND + "`. */}")
# The Smart tool's description names the model and whose key pays; the server fills both in from its key.
MODEL_SENTINEL = "MOBSTER-DOCS-MODEL"


# -- MDX text ----------------------------------------------------------------------------------------------------

CODE_TOKEN = re.compile(r"(?<![\w`$-])(--[a-z][a-z0-9-]*(?:=[^\s,;)]+)?|\$[A-Z][A-Z0-9_]+)")


def escape(text, table=False):
    """Help text as MDX. Options and $VARIABLES become code, so `--app` isn't typeset as an em dash; outside code,
    braces and angle brackets are literal (MDX would read them as an expression or a tag); in a table cell, pipes
    are escaped everywhere."""
    parts = re.split(r"(`[^`]*`)", text)
    parts = [part if part.startswith("`") else CODE_TOKEN.sub(r"`\1`", part) for part in parts]
    out = []
    for part in re.split(r"(`[^`]*`)", "".join(parts)):
        if part.startswith("`") and part.endswith("`") and len(part) > 1:
            out.append(part.replace("|", "\\|") if table else part)
            continue
        part = re.sub(r"([\\{}<>*\[\]])", r"\\\1", part)
        out.append(part.replace("|", "\\|") if table else part)
    return "".join(out)


def prop(value):
    """A JSX attribute value: a JSON string inside braces, so any quote or brace in it stays literal."""
    return "{" + json.dumps(value, ensure_ascii=False) + "}"


def field(name, type_, body, default=None, required=False, post=()):
    """A Mintlify ResponseField: one argument with its type, default and description."""
    attributes = [f"name={prop(name)}", f"type={prop(type_)}"]
    if default:
        attributes.append(f"default={prop(default)}")
    if required:
        attributes.append("required")
    if post:
        attributes.append(f"post={prop(list(post))}")
    if not body.strip():
        return [f"<ResponseField {' '.join(attributes)} />", ""]
    return [f"<ResponseField {' '.join(attributes)}>", body.strip(), "</ResponseField>", ""]


def paragraphs(text):
    """A help description wrapped for a terminal, as paragraphs: blank lines split them, line breaks join."""
    blocks = re.split(r"\n\s*\n", (text or "").strip())
    return [" ".join(line.strip() for line in block.splitlines()) for block in blocks if block.strip()]


def code(text):
    return "`" + text.replace("`", "'") + "`"


def frontmatter(title, sidebar, description):
    return "\n".join(["---", f"title: {json.dumps(title)}", f"sidebarTitle: {json.dumps(sidebar)}",
                      f"description: {json.dumps(description)}", "---", ""])


# -- The CLI -----------------------------------------------------------------------------------------------------

def build_parser():
    """`mobster`'s parser with extensions off: the public tree's commands only."""
    from mobile_agent import __main__ as cli
    from mobile_agent.extensions import Hooks
    with mock.patch.object(cli, "load_extensions", return_value=Hooks()):
        return cli.build_parser(), cli.EVERYDAY


def subparsers(parser):
    return next((a for a in parser._actions if isinstance(a, argparse._SubParsersAction)), None)


def commands_of(parser, order=()):
    """[(name, help, subparser)] in `--help` order: ``order`` first, then the rest as added; aliases once."""
    subs = subparsers(parser)
    if subs is None:
        return []
    helps = {action.dest: action.help for action in subs._choices_actions}
    seen, listed = set(), []
    for name, sub in subs.choices.items():
        if id(sub) in seen:
            continue
        seen.add(id(sub))
        listed.append((name, helps.get(name) or "", sub))
    rank = {name: i for i, name in enumerate(order)}
    return sorted(listed, key=lambda item: (rank.get(item[0], len(rank)), listed.index(item)))


def takes(action):
    """What an argument takes, in plain words for a field's type."""
    if action.nargs == 0:
        return "flag"
    if action.choices and not isinstance(action, argparse._SubParsersAction):
        value = " | ".join(str(choice) for choice in action.choices)
    else:
        value = action.metavar if isinstance(action.metavar, str) else (action.dest or "").upper()
    more = {"?": "optional", "*": "zero or more", "+": "one or more", argparse.REMAINDER: "the rest"}.get(action.nargs)
    return f"{value}, {more}" if more else value


def repeatable(action):
    return isinstance(action, argparse._AppendAction) or type(action).__name__.endswith("Expectation")


def stated_default(help_text):
    """The default an option's help states, "(default: 30)" or "; default: $MOBSTER_ENV_FILE", or None."""
    match = re.search(r"\(default:? ([^)]*)\)", help_text or "") or re.search(r"(?:^|; )default:? ([^;]+)$", help_text or "")
    return match[1].strip() if match else None


def default_of(action):
    """The parser's default, else the one its help states (the command decides it at run time), else None."""
    if isinstance(action, argparse._VersionAction):
        return None
    if action.default in (None, argparse.SUPPRESS) or action.nargs == 0 and action.default is False:
        return stated_default(action.help) or ("off" if action.nargs == 0 else None)
    if action.const is not None and action.nargs == "?":
        return f"{action.default}; {action.const} when given with no value"
    if isinstance(action.default, (list, tuple)):
        return ", ".join(map(str, action.default)) or None
    return str(action.default)


def visible(parser):
    return [a for a in parser._actions if a.help is not argparse.SUPPRESS
            and not isinstance(a, (argparse._HelpAction, argparse._SubParsersAction))]


def argument_fields(parser):
    lines = []
    actions = visible(parser)
    positionals = [a for a in actions if not a.option_strings]
    options = [a for a in actions if a.option_strings]
    if positionals:
        lines += ["**Arguments**", ""]
        for action in positionals:
            metavar = action.metavar if isinstance(action.metavar, str) else action.dest.upper()
            required = action.nargs not in ("?", "*", argparse.REMAINDER)
            lines += field(metavar, takes(action), escape(action.help or ""), required=required)
    if options:
        lines += ["**Options**", ""]
        for action in options:
            lines += field(", ".join(action.option_strings), takes(action), escape(action.help or ""),
                           default=default_of(action), required=action.required,
                           post=["repeatable"] if repeatable(action) else ())
    for group in parser._mutually_exclusive_groups:
        names = [a.option_strings[0] if a.option_strings else (a.metavar or a.dest).upper()
                 for a in group._group_actions if a.help is not argparse.SUPPRESS]
        if len(names) > 1:
            joined = ", ".join(code(n) for n in names[:-1]) + " and " + code(names[-1])
            lines.append(f"{joined} can't be used together" + ("; one is required." if group.required else ".")
                         + "\n")
    return lines


def epilog_block(parser):
    if not parser.epilog:
        return []
    return ["```text", parser.epilog.strip("\n"), "```", ""]


def command_section(prog, help_text, parser, depth):
    heading = "#" * depth
    lines = [f"{heading} {code(prog)}", ""]
    described = paragraphs(parser.description) or ([help_text[:1].upper() + help_text[1:] + "."] if help_text else [])
    lines += [p for paragraph in described for p in (escape(paragraph), "")]
    if parser.get_default("stub_command"):
        # A track's command that hasn't landed: devtools.py gives it its help, and the stub only says it isn't here.
        lines += [f"This build doesn't have {code(prog)} yet: it says so and exits 3.", ""]
    lines += argument_fields(parser)
    lines += epilog_block(parser)
    children = commands_of(parser)
    if children:
        lines += ["| Command | What it does |", "|---|---|"]
        lines += [f"| [{code(f'{prog} {name}')}](#{anchor(f'{prog} {name}')}) | {escape(child_help, True)} |"
                  for name, child_help, _ in children]
        lines.append("")
        for name, child_help, child in children:
            lines += command_section(f"{prog} {name}", child_help, child, min(depth + 1, 4))
    return lines


def anchor(heading):
    """Mintlify's heading slug: lowercase, spaces to dashes, underscores kept, other punctuation dropped."""
    return re.sub(r"[^a-z0-9 _-]", "", heading.lower()).strip().replace(" ", "-")


def cli_page():
    parser, everyday = build_parser()
    commands = commands_of(parser, everyday)
    lines = [frontmatter("Every command and option", "CLI options",
                         "Every mobster command, subcommand, argument and option with its default, generated from "
                         "the command's own parser."),
             NOTICE.replace("SOURCE", "the argparse parsers in mobile_agent/__main__.py and each command's cli module"),
             "",
             "This page is generated from the parsers `mobster` itself runs, so it lists exactly what this version "
             "accepts. `mobster <command> --help` prints the same text in the terminal. The "
             "[CLI reference](/cli) explains the commands with examples and exit codes.",
             "",
             "Options must be spelled in full: `--exec` is not `--execute`. A command's options can go before or "
             "after its name.",
             "",
             "| Command | What it does |", "|---|---|"]
    lines += [f"| [{code(f'mobster {name}')}](#{anchor(f'mobster {name}')}) | {escape(help_text, True)} |"
              for name, help_text, _ in commands]
    lines += ["", "## `mobster`", "",
              "`mobster` with no command opens the terminal UI. These options belong to it (and to "
              "`mobster tui`).", ""]
    lines += argument_fields(parser)
    for name, help_text, sub in commands:
        lines += command_section(f"mobster {name}", help_text, sub, 2)
    return "\n".join(lines).rstrip("\n") + "\n"


# -- The MCP tools -----------------------------------------------------------------------------------------------

KINDS = {
    "read": ("Read-only", "Reads the screen or Mobster's state and changes nothing."),
    "acts": ("Acts on the device", "Taps, types, opens or installs on a simulator or a real iPhone. A client that "
                                   "asks before destructive or open-world calls asks before these."),
    "local": ("Local", "Not read-only, and not marked destructive or open-world: it starts, judges, saves or stops "
                       "Mobster's own runs."),
}


def kind_of(annotations):
    if annotations.get("readOnlyHint"):
        return "read"
    if annotations.get("destructiveHint") or annotations.get("openWorldHint"):
        return "acts"
    return "local"


def tool_list():
    """Every tool, `verify` (Smart) and the tracks' tools included: ToolSets built with a placeholder key and model,
    `--allow-files` on, no device, no I/O. The instructions are the key-less server's (core and the tracks')."""
    import tempfile
    from mobile_agent import tracks
    from mobile_agent.mcp_server import registry, tools as mcp
    tracks.load()  # the tracks' MCP tools (mcp_server/registry.py), as `mobster mcp` loads them at startup
    with tempfile.TemporaryDirectory() as folder:
        keyless = mcp.ToolSet(runs_dir=folder, version="0", devices=lambda: [], allow_files=True)
        smart = mcp.ToolSet(runs_dir=folder, key="placeholder", smart_model=MODEL_SENTINEL, version="0",
                            devices=lambda: [], allow_files=True)
        listed = {tool["name"]: tool for tool in smart.list_tools()}
        offered_without_key = {tool["name"] for tool in keyless.list_tools()}
        instructions = keyless.instructions()
    for tool in listed.values():
        tool["description"] = re.sub(re.escape(MODEL_SENTINEL) + r", on the user's \w+ key",
                                     "`<model>`, on the user's `<provider>` key", tool["description"])
        tool["smart_only"] = tool["name"] not in offered_without_key
        tool["files_only"] = tool["name"] in registry.FILE_TOOLS
    return list(listed.values()), instructions


def type_of(schema):
    """A short, plain type for a property schema, such as "string, length 1–128" or "up | down | left | right"."""
    kind = schema.get("type")
    if "enum" in schema:
        text = " | ".join(json.dumps(v) for v in schema["enum"])
    elif kind == "array":
        text = "array of " + (type_of(schema.get("items", {})) if schema.get("items") else "any")
    elif kind == "object" and "properties" in schema:
        text = "object: " + ", ".join(schema["properties"])
    else:
        text = kind or "any"
    bounds = []
    for low, high, word in (("minimum", "maximum", ""), ("exclusiveMinimum", "maximum", "above "),
                            ("minLength", "maxLength", "length "), ("minItems", "maxItems", "items ")):
        if low in schema and high in schema and schema.get(high) is not None:
            bounds.append(f"{word}{schema[low]:,}–{schema[high]:,}" if not word.startswith("above")
                          else f"more than {schema[low]:,}, at most {schema[high]:,}")
        elif low in schema:
            bounds.append(f"{word}at least {schema[low]:,}" if not word.startswith("above")
                          else f"more than {schema[low]:,}")
        elif high in schema and low == "minimum":
            bounds.append(f"at most {schema[high]:,}")
        elif high in schema and low in ("minLength", "minItems"):
            bounds.append(f"{word}at most {schema[high]:,}")
    if "pattern" in schema:
        bounds.append("matching " + schema["pattern"])
    return text + (f" ({', '.join(bounds)})" if bounds else "")


def tool_section(tool):
    name, schema, annotations = tool["name"], tool["inputSchema"], tool["annotations"]
    kind, why = KINDS[kind_of(annotations)]
    hints = " · ".join(f"`{key}: {json.dumps(value)}`" for key, value in annotations.items())
    lines = [f"## {code(name)}", "", escape(tool["description"]), "",
             f"**{kind}.** {why}" + (" Listed only when the server has an OpenAI or Anthropic key and isn't "
                                     "started with `--keyless`." if tool["smart_only"] else "")
             + (" Listed only when the server is started with `--allow-files`." if tool["files_only"] else ""), "",
             f"Annotations: {hints}", ""]
    properties, required = schema.get("properties", {}), set(schema.get("required", []))
    if properties:
        lines += ["**Arguments**", ""]
        for prop_name, spec in properties.items():
            default = json.dumps(spec["default"]) if "default" in spec else None
            lines += field(prop_name, type_of(spec), escape(spec.get("description", "")), default=default,
                           required=prop_name in required)
    else:
        lines += ["Takes no arguments.", ""]
    lines += [f'<Accordion title="Input schema of {name}">', "", "```json",
              json.dumps(schema, indent=2, ensure_ascii=False), "```", "", "</Accordion>", ""]
    return lines


def mcp_page():
    tools, instructions = tool_list()
    lines = [frontmatter("MCP tools", "MCP tools",
                         "Every tool mobster mcp offers, with its arguments, input schema and whether it only reads "
                         "or acts on a device, generated from the server's tool list."),
             NOTICE.replace("SOURCE", "the tool lists in mobile_agent/mcp_server/tools.py and the tracks' "
                                      "providers (mobile_agent/mcp_server/registry.py)"),
             "",
             "This page is generated from the tool list `mobster mcp` serves, so it matches what your agent sees "
             "in `tools/list`. [Add Mobster to your agent](/agents) sets the server up, and "
             "[MCP server](/mcp-server) explains the loops the tools are for.",
             "",
             "Each tool carries MCP annotations. Read-only tools change nothing. Tools that act on a device are "
             "marked destructive and open-world, so a client that asks before such calls asks before these. On a "
             "real iPhone they act for real: a tap on Send sends.",
             "",
             "| Tool | Kind | What it does |", "|---|---|---|"]
    for tool in tools:
        kind = (KINDS[kind_of(tool["annotations"])][0] + (" (Smart only)" if tool["smart_only"] else "")
                + (" (`--allow-files`)" if tool["files_only"] else ""))
        lines.append(f"| [{code(tool['name'])}](#{anchor(tool['name'])}) | {kind} | "
                     f"{escape(tool['description'], True)} |")
    lines += ["", "## The server's instructions", "",
              "The server sends these instructions to the client when it connects. With a key, it adds a sentence "
              "naming the Smart model and whose key pays for it.", "",
              "> " + escape(instructions), ""]
    for tool in tools:
        lines += tool_section(tool)
    return "\n".join(lines).rstrip("\n") + "\n"


# -- Main --------------------------------------------------------------------------------------------------------

# -- llms.txt ----------------------------------------------------------------------------------------------------

# The Optional section: mobster.dev's pages for the people the docs don't cover (llmstxt.org's "Optional").
ELSEWHERE = [
    ("Mobster for Mac", "https://mobster.dev", "Download the Mac app, see pricing and buy a license."),
    ("Integrations", "https://mobster.dev/integrations",
     "Setting Mobster up in Claude Code, Codex, Cursor, Claude Desktop, VS Code, Gemini CLI and other agents."),
    ("Compare", "https://mobster.dev/compare", "Mobster beside TapKit, Maestro, Appium and XCUITest."),
    ("Blog", "https://mobster.dev/blog", "Guides and notes from the people who make Mobster."),
    ("Mobster CLI on GitHub", "https://github.com/RadishSoftware/mobster",
     "The open-source CLI, MCP server and agent loop, under MIT."),
]


def nav_sections(node, trail=()):
    """(heading, [page]) for each group of docs.json's navigation, in order: "Tab: Group", or the tab alone."""
    if isinstance(node, list):
        for item in node:
            yield from nav_sections(item, trail)
        return
    if not isinstance(node, dict):
        return
    name = node.get("tab") or node.get("group")
    here = trail + ((name,) if name else ())
    pages = [p for p in node.get("pages", []) if isinstance(p, str)]
    if pages:
        yield ": ".join(dict.fromkeys(here)), pages
    for item in node.get("pages", []):
        if isinstance(item, dict):
            yield from nav_sections(item, here)
    for key in ("tabs", "groups"):
        if key in node:
            yield from nav_sections(node[key], here)


def page_meta(page):
    """A docs page's frontmatter title and description."""
    import yaml
    path = next(DOCS / f"{page}{suffix}" for suffix in (".mdx", ".md") if (DOCS / f"{page}{suffix}").is_file())
    match = re.match(r"---\n(.*?)\n---\n", path.read_text(), re.S)
    meta = yaml.safe_load(match[1]) if match else {}
    return meta.get("title") or page, " ".join(str(meta.get("description") or "").split())


def llms_txt():
    site = json.loads((DOCS / "docs.json").read_text())
    lines = [f"# {site['name']}", "", f"> {site['description']}", "",
             "Mobster for Mac is the app: guided setup for each iPhone, a live view, conversations with approvals, "
             "memory, files, voice, history and schedules. Mobster CLI is its free, open-source engine: the "
             "`mobster` command, its MCP server and the agent loop. Every page below is Markdown at its link. The "
             f"whole site in one file is {SITE_URL}/llms-full.txt.", ""]
    for heading, pages in nav_sections(site["navigation"]):
        lines += [f"## {heading}", ""]
        for page in pages:
            title, description = page_meta(page)
            lines.append(f"- [{title}]({SITE_URL}/{page}.md)" + (f": {description}" if description else ""))
        lines.append("")
    lines += ["## Optional", ""]
    lines += [f"- [{title}]({url}): {description}" for title, url, description in ELSEWHERE]
    return "\n".join(lines) + "\n"


PAGES = {REFERENCE / "cli.mdx": cli_page, REFERENCE / "mcp-tools.mdx": mcp_page, DOCS / "llms.txt": llms_txt}


def stale():
    """The pages whose committed text differs from what the code generates now: [(path, expected)]."""
    out = []
    for path, render in PAGES.items():
        text = render()
        if not path.is_file() or path.read_text() != text:
            out.append((path, text))
    return out


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--check", action="store_true", help="exit 1 if a page is stale instead of writing it")
    args = parser.parse_args(argv)
    changed = stale()
    if args.check:
        for path, _ in changed:
            print(f"{path.relative_to(ROOT)} is stale: run `{COMMAND}`", file=sys.stderr)
        return 1 if changed else 0
    REFERENCE.mkdir(parents=True, exist_ok=True)
    for path, text in changed:
        path.write_text(text)
        print(f"wrote {path.relative_to(ROOT)}")
    if not changed:
        print("docs/reference and docs/llms.txt are up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
